# Demo-specific configuration
demo:
  enabled: true

# Configuration for the underlying SkyPilot chart
skypilot:
  apiService:
    # Enable development mode for demo
    skypilotDev: true
    
    # Disable all authentication for demo
    enableUserManagement: false
    enableServiceAccounts: false
    
    # Skip resource check for demo
    skipResourceCheck: true
    
    # Reduce resource requirements for demo
    resources:
      requests:
        cpu: "3"
        memory: "12Gi"
      limits:
        cpu: "3"
        memory: "12Gi"
    
    # Enable demo mode with additional environment variables
    # The SKYPILOT_INTERNAL_APPLY_DEMO_PATCH env var is used by the parent chart
    # to detect demo mode and automatically add the demo ConfigMap volumes
    extraEnv:
    - name: SKYPILOT_INTERNAL_APPLY_DEMO_PATCH
      value: "true"

    preDeployHook: |-
      pip install json5

    # Mount demo ConfigMaps as volumes
    # Using predictable ConfigMap names that match the release name pattern
    extraVolumes:
    - name: demo-users
      configMap:
        name: skypilot-demo-demo-users
    - name: demo-clusters
      configMap:
        name: skypilot-demo-demo-clusters
    - name: demo-jobs
      configMap:
        name: skypilot-demo-demo-jobs
    - name: demo-cluster-jobs
      configMap:
        name: skypilot-demo-demo-cluster-jobs
    - name: demo-volumes
      configMap:
        name: skypilot-demo-demo-volumes
    - name: demo-workspaces
      configMap:
        name: skypilot-demo-demo-workspaces
    - name: demo-infrastructure
      configMap:
        name: skypilot-demo-demo-infrastructure

    extraVolumeMounts:
    - name: demo-users
      mountPath: /etc/skypilot/demo/mock_data/mock_users.json5
      subPath: mock_users.json5
      readOnly: true
    - name: demo-clusters
      mountPath: /etc/skypilot/demo/mock_data/mock_clusters.json5
      subPath: mock_clusters.json5
      readOnly: true
    - name: demo-jobs
      mountPath: /etc/skypilot/demo/mock_data/mock_jobs.json5
      subPath: mock_jobs.json5
      readOnly: true
    - name: demo-cluster-jobs
      mountPath: /etc/skypilot/demo/mock_data/mock_cluster_jobs.json5
      subPath: mock_cluster_jobs.json5
      readOnly: true
    - name: demo-volumes
      mountPath: /etc/skypilot/demo/mock_data/mock_volumes.json5
      subPath: mock_volumes.json5
      readOnly: true
    - name: demo-workspaces
      mountPath: /etc/skypilot/demo/mock_data/mock_workspaces.json5
      subPath: mock_workspaces.json5
      readOnly: true
    - name: demo-infrastructure
      mountPath: /etc/skypilot/demo/mock_data/mock_infrastructure.json5
      subPath: mock_infrastructure.json5
      readOnly: true
      
    # Deployment strategy configuration
    deploymentStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0

  # Enable ingress without authentication for demo
  ingress:
    enabled: true
    # The base path of API server - can be overridden via --set
    path: '/'
    # No auth required - remove auth configurations
    authSecret: null
    authCredentials: null
    # Disable OAuth2 proxy
    oauth2-proxy:
      enabled: false

  # Disable persistent storage for demo mode - no state to persist
  storage:
    enabled: false 
