# Demo-specific values for SkyPilot Helm chart
# This file provides minimal demo-specific configuration

apiService:
  # Enable development mode for demo
  skypilotDev: true
  
  # Disable all authentication for demo
  enableUserManagement: false
  enableServiceAccounts: false
  
  # Reduce resource requirements for demo
  resources:
    requests:
      cpu: "3"
      memory: "12Gi"
    limits:
      cpu: "3"
      memory: "12Gi"
  
  # Enable demo mode with additional environment variables
  extraEnv:
  - name: SKYPILOT_INTERNAL_APPLY_DEMO_PATCH
    value: "true"

  preDeployHook: |-
    pip install json5
    

# Enable ingress without authentication for demo
ingress:
  enabled: true
  # No auth required - remove auth configurations
  authSecret: null
  authCredentials: null
  # Disable OAuth2 proxy
  oauth2-proxy:
    enabled: false

# Use smaller storage for demo
storage:
  enabled: true
  size: 5Gi
